<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.19" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.19" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.19">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="MySql.Data" Version="9.4.0" />
    <PackageReference Include="MySql.EntityFrameworkCore" Version="9.0.6" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="8.0.3" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql.Design" Version="1.1.2" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\uploads\Expense\" />
    <Folder Include="wwwroot\uploads\User\" />
    <Folder Include="wwwroot\uploads\Order\" />
    <Folder Include="wwwroot\uploads\Payment\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\uploads\Invoice\8ad5312b-cf6a-40e5-a393-a5b4b1715623.jpg" />
  </ItemGroup>

</Project>
