// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShairiStore;

#nullable disable

namespace ShairiStore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251003124430_AddInventoryDbSet")]
    partial class AddInventoryDbSet
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ShairiStore.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FullName")
                        .HasColumnType("longtext");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ShairiStore.Models.Brand", b =>
                {
                    b.Property<int>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BrandId"));

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("BrandId");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            BrandId = 1,
                            BrandName = "Zarafa",
                            IsActive = true
                        },
                        new
                        {
                            BrandId = 2,
                            BrandName = "Golden Grain",
                            IsActive = true
                        },
                        new
                        {
                            BrandId = 3,
                            BrandName = "Shan Foods",
                            IsActive = true
                        },
                        new
                        {
                            BrandId = 4,
                            BrandName = "Rafi Daal Factory",
                            IsActive = true
                        },
                        new
                        {
                            BrandId = 5,
                            BrandName = "Baison A",
                            IsActive = true
                        },
                        new
                        {
                            BrandId = 6,
                            BrandName = "Baison B",
                            IsActive = true
                        },
                        new
                        {
                            BrandId = 7,
                            BrandName = "Himalayan Chef",
                            IsActive = true
                        },
                        new
                        {
                            BrandId = 8,
                            BrandName = "Nimcos",
                            IsActive = true
                        },
                        new
                        {
                            BrandId = 9,
                            BrandName = "Sunridge",
                            IsActive = true
                        },
                        new
                        {
                            BrandId = 10,
                            BrandName = "Bake Parlor",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("ShairiStore.Models.BrokerInfo", b =>
                {
                    b.Property<int>("BrokerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BrokerId"));

                    b.Property<double?>("BrokerCommission")
                        .HasColumnType("double");

                    b.Property<string>("BrokerName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("BrokerId");

                    b.ToTable("Brokers");

                    b.HasData(
                        new
                        {
                            BrokerId = 1,
                            BrokerCommission = 2.5,
                            BrokerName = "Kamal Subhani",
                            IsActive = true
                        },
                        new
                        {
                            BrokerId = 2,
                            BrokerCommission = 2.5,
                            BrokerName = "Ali Akbar",
                            IsActive = true
                        },
                        new
                        {
                            BrokerId = 3,
                            BrokerCommission = 2.5,
                            BrokerName = "Amjad Hussain",
                            IsActive = true
                        },
                        new
                        {
                            BrokerId = 4,
                            BrokerCommission = 2.5,
                            BrokerName = "Nasir Ali",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("ShairiStore.Models.Inventory", b =>
                {
                    b.Property<int>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("InventoryId"));

                    b.Property<int>("AvailableQuantityKgs")
                        .HasColumnType("int");

                    b.Property<double>("OneMonRate")
                        .HasColumnType("double");

                    b.Property<int>("PendingQuantityKgs")
                        .HasColumnType("int");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime(6)");

                    b.HasKey("InventoryId");

                    b.HasIndex("SubCategoryId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("inventories");
                });

            modelBuilder.Entity("ShairiStore.Models.InvoiceStatus", b =>
                {
                    b.Property<int>("InvoiceStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("InvoiceStatusId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("InvoiceStatusId");

                    b.ToTable("InvoiceStatuses");

                    b.HasData(
                        new
                        {
                            InvoiceStatusId = 1,
                            IsActive = false,
                            StatusName = "Pending"
                        },
                        new
                        {
                            InvoiceStatusId = 2,
                            IsActive = false,
                            StatusName = "Paid"
                        },
                        new
                        {
                            InvoiceStatusId = 3,
                            IsActive = false,
                            StatusName = "Partially Paid"
                        },
                        new
                        {
                            InvoiceStatusId = 4,
                            IsActive = false,
                            StatusName = "Cancelled"
                        });
                });

            modelBuilder.Entity("ShairiStore.Models.NotificationDetails", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NotificationContent")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("NotificationCreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NotificationGeneratedBy")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NotificationModule")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NotificationRecepient")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NotificationTitle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("NotificationTypeId")
                        .HasColumnType("int");

                    b.Property<string>("RedirectURL")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("NotificationId");

                    b.HasIndex("NotificationGeneratedBy");

                    b.HasIndex("NotificationTypeId");

                    b.ToTable("NotificationDetails");
                });

            modelBuilder.Entity("ShairiStore.Models.NotificationType", b =>
                {
                    b.Property<int>("NotificationTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("NotificationTypeId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("NotificationTypeId");

                    b.ToTable("NotificationTypes");

                    b.HasData(
                        new
                        {
                            NotificationTypeId = 1,
                            IsActive = true,
                            Type = "User Created"
                        },
                        new
                        {
                            NotificationTypeId = 2,
                            IsActive = true,
                            Type = "User Updated"
                        },
                        new
                        {
                            NotificationTypeId = 3,
                            IsActive = true,
                            Type = "Order Created"
                        },
                        new
                        {
                            NotificationTypeId = 4,
                            IsActive = true,
                            Type = "Order Updated"
                        },
                        new
                        {
                            NotificationTypeId = 5,
                            IsActive = true,
                            Type = "Invoice Created"
                        },
                        new
                        {
                            NotificationTypeId = 6,
                            IsActive = true,
                            Type = "Invoice Paid"
                        },
                        new
                        {
                            NotificationTypeId = 7,
                            IsActive = true,
                            Type = "Payment Received"
                        });
                });

            modelBuilder.Entity("ShairiStore.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<double>("BrokerAmount")
                        .HasColumnType("double");

                    b.Property<int>("BrokerId")
                        .HasColumnType("int");

                    b.Property<double>("CalculatedAmount")
                        .HasColumnType("double");

                    b.Property<string>("OrderBy")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("OrderName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OrderNotes")
                        .HasColumnType("longtext");

                    b.Property<string>("OrderScreenShot")
                        .HasColumnType("longtext");

                    b.Property<int>("OrderStatusId")
                        .HasColumnType("int");

                    b.Property<int>("OrderTypeId")
                        .HasColumnType("int");

                    b.Property<double>("OtherExpenses")
                        .HasColumnType("double");

                    b.Property<int>("SellerId")
                        .HasColumnType("int");

                    b.Property<double>("TotalAmount")
                        .HasColumnType("double");

                    b.Property<double?>("TotalPendingBalance")
                        .HasColumnType("double");

                    b.Property<double?>("TotalPendingKgs")
                        .HasColumnType("double");

                    b.Property<double?>("TotalPendingQuantity")
                        .HasColumnType("double");

                    b.Property<double?>("TotalReceivedKgs")
                        .HasColumnType("double");

                    b.Property<double?>("TotalReceivedQuantity")
                        .HasColumnType("double");

                    b.Property<double>("TotalRequiredKgs")
                        .HasColumnType("double");

                    b.Property<double>("TotalRequiredQuantity")
                        .HasColumnType("double");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("BrokerId");

                    b.HasIndex("OrderBy");

                    b.HasIndex("OrderStatusId");

                    b.HasIndex("OrderTypeId");

                    b.HasIndex("SellerId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ShairiStore.Models.OrderCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Daal",
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Baison",
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Chawaal",
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Channay",
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Attah",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("ShairiStore.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OrderDetailId"));

                    b.Property<double>("CalculatedAmount")
                        .HasColumnType("double");

                    b.Property<double>("OneMonRate")
                        .HasColumnType("double");

                    b.Property<string>("OrderBy")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("OrderStatusId")
                        .HasColumnType("int");

                    b.Property<double>("OtherExpenses")
                        .HasColumnType("double");

                    b.Property<double?>("PendingBalance")
                        .HasColumnType("double");

                    b.Property<double?>("PendingKgs")
                        .HasColumnType("double");

                    b.Property<double?>("PendingQuantity")
                        .HasColumnType("double");

                    b.Property<double?>("ReceivedKgs")
                        .HasColumnType("double");

                    b.Property<double?>("ReceivedQuantity")
                        .HasColumnType("double");

                    b.Property<double>("RequiredKgs")
                        .HasColumnType("double");

                    b.Property<double>("RequiredQuantity")
                        .HasColumnType("double");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.Property<double>("TotalAmount")
                        .HasColumnType("double");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("OrderBy");

                    b.HasIndex("OrderId");

                    b.HasIndex("OrderStatusId");

                    b.HasIndex("SubCategoryId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("ShairiStore.Models.OrderInvoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("InvoiceId"));

                    b.Property<double>("InvoiceAmount")
                        .HasColumnType("double");

                    b.Property<string>("InvoiceBy")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("InvoiceStatusId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentScreenshot")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("PendingAmount")
                        .HasColumnType("double");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("InvoiceId");

                    b.HasIndex("InvoiceBy");

                    b.HasIndex("InvoiceStatusId");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("OrderInvoices");
                });

            modelBuilder.Entity("ShairiStore.Models.OrderPayment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<double>("AmountPaid")
                        .HasColumnType("double");

                    b.Property<int>("InvoiceStatusId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("PaidBy")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentScreenshot")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("RemainingAmount")
                        .HasColumnType("double");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("PaymentId");

                    b.HasIndex("InvoiceStatusId");

                    b.HasIndex("OrderId");

                    b.HasIndex("PaidBy");

                    b.HasIndex("PaymentMethodId");

                    b.ToTable("OrderPayments");
                });

            modelBuilder.Entity("ShairiStore.Models.OrderStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("StatusId");

                    b.ToTable("OrderStatuses");

                    b.HasData(
                        new
                        {
                            StatusId = 1,
                            IsActive = true,
                            Status = "Placed"
                        },
                        new
                        {
                            StatusId = 2,
                            IsActive = true,
                            Status = "Confirmed"
                        },
                        new
                        {
                            StatusId = 3,
                            IsActive = true,
                            Status = "Processing"
                        },
                        new
                        {
                            StatusId = 4,
                            IsActive = true,
                            Status = "Shipped"
                        },
                        new
                        {
                            StatusId = 5,
                            IsActive = true,
                            Status = "Delivered"
                        },
                        new
                        {
                            StatusId = 6,
                            IsActive = true,
                            Status = "Rejected"
                        },
                        new
                        {
                            StatusId = 7,
                            IsActive = true,
                            Status = "OnHold"
                        },
                        new
                        {
                            StatusId = 8,
                            IsActive = true,
                            Status = "Cancelled"
                        });
                });

            modelBuilder.Entity("ShairiStore.Models.OrderSubCategory", b =>
                {
                    b.Property<int>("SubCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SubCategoryId"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<double>("OneMonRate")
                        .HasColumnType("double");

                    b.Property<string>("SubCategoryName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("SubCategoryId");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.ToTable("SubCategories");

                    b.HasData(
                        new
                        {
                            SubCategoryId = 1,
                            BrandId = 3,
                            CategoryId = 1,
                            IsActive = true,
                            OneMonRate = 100.0,
                            SubCategoryName = "Daal Mash"
                        },
                        new
                        {
                            SubCategoryId = 2,
                            BrandId = 4,
                            CategoryId = 1,
                            IsActive = true,
                            OneMonRate = 100.0,
                            SubCategoryName = "Daal Mash"
                        },
                        new
                        {
                            SubCategoryId = 3,
                            BrandId = 3,
                            CategoryId = 1,
                            IsActive = true,
                            OneMonRate = 150.0,
                            SubCategoryName = "Daal Channa"
                        },
                        new
                        {
                            SubCategoryId = 4,
                            BrandId = 4,
                            CategoryId = 1,
                            IsActive = true,
                            OneMonRate = 500.0,
                            SubCategoryName = "Daal Channa"
                        },
                        new
                        {
                            SubCategoryId = 5,
                            BrandId = 5,
                            CategoryId = 2,
                            IsActive = true,
                            OneMonRate = 100.0,
                            SubCategoryName = "Baison Sub Category 1"
                        },
                        new
                        {
                            SubCategoryId = 6,
                            BrandId = 6,
                            CategoryId = 2,
                            IsActive = true,
                            OneMonRate = 100.0,
                            SubCategoryName = "Baison Sub Category 1"
                        },
                        new
                        {
                            SubCategoryId = 7,
                            BrandId = 5,
                            CategoryId = 2,
                            IsActive = true,
                            OneMonRate = 150.0,
                            SubCategoryName = "Baison Sub Category 2"
                        },
                        new
                        {
                            SubCategoryId = 8,
                            BrandId = 6,
                            CategoryId = 2,
                            IsActive = true,
                            OneMonRate = 500.0,
                            SubCategoryName = "Baison Sub Category 2"
                        },
                        new
                        {
                            SubCategoryId = 9,
                            BrandId = 1,
                            CategoryId = 3,
                            IsActive = true,
                            OneMonRate = 100.0,
                            SubCategoryName = "Basmati Rice Premium"
                        },
                        new
                        {
                            SubCategoryId = 10,
                            BrandId = 2,
                            CategoryId = 3,
                            IsActive = true,
                            OneMonRate = 100.0,
                            SubCategoryName = "Basmati Rice Premium"
                        },
                        new
                        {
                            SubCategoryId = 11,
                            BrandId = 1,
                            CategoryId = 3,
                            IsActive = true,
                            OneMonRate = 150.0,
                            SubCategoryName = "Basmati Rice Average"
                        },
                        new
                        {
                            SubCategoryId = 12,
                            BrandId = 2,
                            CategoryId = 3,
                            IsActive = true,
                            OneMonRate = 500.0,
                            SubCategoryName = "Basmati Rice Average"
                        },
                        new
                        {
                            SubCategoryId = 13,
                            BrandId = 7,
                            CategoryId = 4,
                            IsActive = true,
                            OneMonRate = 100.0,
                            SubCategoryName = "Safaid Channy"
                        },
                        new
                        {
                            SubCategoryId = 14,
                            BrandId = 8,
                            CategoryId = 4,
                            IsActive = true,
                            OneMonRate = 100.0,
                            SubCategoryName = "Safaid Channy"
                        },
                        new
                        {
                            SubCategoryId = 15,
                            BrandId = 7,
                            CategoryId = 4,
                            IsActive = true,
                            OneMonRate = 150.0,
                            SubCategoryName = "kaalay Channy"
                        },
                        new
                        {
                            SubCategoryId = 16,
                            BrandId = 8,
                            CategoryId = 4,
                            IsActive = true,
                            OneMonRate = 500.0,
                            SubCategoryName = "Kaalay Channy"
                        },
                        new
                        {
                            SubCategoryId = 17,
                            BrandId = 9,
                            CategoryId = 5,
                            IsActive = true,
                            OneMonRate = 100.0,
                            SubCategoryName = "Saifaid Attah Premium"
                        },
                        new
                        {
                            SubCategoryId = 18,
                            BrandId = 10,
                            CategoryId = 5,
                            IsActive = true,
                            OneMonRate = 100.0,
                            SubCategoryName = "Saifaid Attah Premium"
                        },
                        new
                        {
                            SubCategoryId = 19,
                            BrandId = 9,
                            CategoryId = 5,
                            IsActive = true,
                            OneMonRate = 150.0,
                            SubCategoryName = "Mix Attah Premium"
                        },
                        new
                        {
                            SubCategoryId = 20,
                            BrandId = 10,
                            CategoryId = 5,
                            IsActive = true,
                            OneMonRate = 500.0,
                            SubCategoryName = "Mix Attah Premium"
                        });
                });

            modelBuilder.Entity("ShairiStore.Models.OrderType", b =>
                {
                    b.Property<int>("OrderTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OrderTypeId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("OrderTypeId");

                    b.ToTable("OrderTypes");

                    b.HasData(
                        new
                        {
                            OrderTypeId = 1,
                            IsActive = true,
                            TypeName = "Incoming Order"
                        },
                        new
                        {
                            OrderTypeId = 2,
                            IsActive = true,
                            TypeName = "Outgoing Order"
                        });
                });

            modelBuilder.Entity("ShairiStore.Models.PaymentMethod", b =>
                {
                    b.Property<int>("PaymentMethodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PaymentMethodId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PaymentMode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("PaymentMethodId");

                    b.ToTable("PaymentMethods");

                    b.HasData(
                        new
                        {
                            PaymentMethodId = 1,
                            IsActive = false,
                            PaymentMode = "Cash"
                        },
                        new
                        {
                            PaymentMethodId = 2,
                            IsActive = false,
                            PaymentMode = "Online Transfer"
                        },
                        new
                        {
                            PaymentMethodId = 3,
                            IsActive = false,
                            PaymentMode = "Bank Checque"
                        });
                });

            modelBuilder.Entity("ShairiStore.Models.SellerInfo", b =>
                {
                    b.Property<int>("SellerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SellerId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SellerName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("SellerId");

                    b.ToTable("Sellers");

                    b.HasData(
                        new
                        {
                            SellerId = 1,
                            IsActive = true,
                            SellerName = "Bilal Waqar"
                        },
                        new
                        {
                            SellerId = 2,
                            IsActive = true,
                            SellerName = "Ahmad Waqar"
                        },
                        new
                        {
                            SellerId = 3,
                            IsActive = true,
                            SellerName = "Haris Akram"
                        },
                        new
                        {
                            SellerId = 4,
                            IsActive = true,
                            SellerName = "Hafiz Asif Akbar"
                        });
                });

            modelBuilder.Entity("ShairiStore.Models.Warehouse", b =>
                {
                    b.Property<int>("WarehouseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("WarehouseId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("WarehouseAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("WarehouseName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("WarehouseId");

                    b.ToTable("Warehouses");

                    b.HasData(
                        new
                        {
                            WarehouseId = 1,
                            IsActive = false,
                            WarehouseAddress = "Usman Shairi Home lahore",
                            WarehouseName = "Dehli Gate Warehouse"
                        },
                        new
                        {
                            WarehouseId = 2,
                            IsActive = false,
                            WarehouseAddress = "Akbari mandi lahore",
                            WarehouseName = "Akbari Mandi Shop"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ShairiStore.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ShairiStore.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShairiStore.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ShairiStore.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShairiStore.Models.Inventory", b =>
                {
                    b.HasOne("ShairiStore.Models.OrderSubCategory", "OrderSubCategory")
                        .WithMany()
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShairiStore.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderSubCategory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShairiStore.Models.NotificationDetails", b =>
                {
                    b.HasOne("ShairiStore.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("NotificationGeneratedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShairiStore.Models.NotificationType", "NotificationType")
                        .WithMany()
                        .HasForeignKey("NotificationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NotificationType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShairiStore.Models.Order", b =>
                {
                    b.HasOne("ShairiStore.Models.BrokerInfo", "Broker")
                        .WithMany()
                        .HasForeignKey("BrokerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShairiStore.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("OrderBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShairiStore.Models.OrderStatus", "OrderStatus")
                        .WithMany()
                        .HasForeignKey("OrderStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShairiStore.Models.OrderType", "OrderType")
                        .WithMany()
                        .HasForeignKey("OrderTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShairiStore.Models.SellerInfo", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShairiStore.Models.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Broker");

                    b.Navigation("OrderStatus");

                    b.Navigation("OrderType");

                    b.Navigation("Seller");

                    b.Navigation("User");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("ShairiStore.Models.OrderDetail", b =>
                {
                    b.HasOne("ShairiStore.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("OrderBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShairiStore.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShairiStore.Models.OrderStatus", "OrderStatus")
                        .WithMany()
                        .HasForeignKey("OrderStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShairiStore.Models.OrderSubCategory", "OrderSubCategory")
                        .WithMany()
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("OrderStatus");

                    b.Navigation("OrderSubCategory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShairiStore.Models.OrderInvoice", b =>
                {
                    b.HasOne("ShairiStore.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("InvoiceBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShairiStore.Models.InvoiceStatus", "InvoiceStatus")
                        .WithMany()
                        .HasForeignKey("InvoiceStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShairiStore.Models.Order", "Orders")
                        .WithOne("OrderInvoice")
                        .HasForeignKey("ShairiStore.Models.OrderInvoice", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvoiceStatus");

                    b.Navigation("Orders");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShairiStore.Models.OrderPayment", b =>
                {
                    b.HasOne("ShairiStore.Models.InvoiceStatus", "InvoiceStatus")
                        .WithMany()
                        .HasForeignKey("InvoiceStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShairiStore.Models.Order", "Order")
                        .WithMany("OrderPayments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShairiStore.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("PaidBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShairiStore.Models.PaymentMethod", "PaymentMethod")
                        .WithMany()
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvoiceStatus");

                    b.Navigation("Order");

                    b.Navigation("PaymentMethod");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShairiStore.Models.OrderSubCategory", b =>
                {
                    b.HasOne("ShairiStore.Models.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShairiStore.Models.OrderCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ShairiStore.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("OrderInvoice");

                    b.Navigation("OrderPayments");
                });
#pragma warning restore 612, 618
        }
    }
}
